---
baseURL: "https://observeproject.github.io/sites/"
# baseURL: ""
languageCode: "en-us"
title: "Mixins for Observability Stack"

theme: 'ace'

# Google analytics
# googleAnalytics: UA-123456789-1

permalinks:
  post: /:filename/

params:
  project_name: Mixins for Observability Stack

  project_tagline: Combination of alerts, recording rules, and dashboards for Observability Stack components

  disableSearch: true
  disableReadmoreNav: true

markup:
  highlight:
    style: monokailight

menu:
  shortcuts:
    - name: Homepage
      url: /
      weight: 1
    - name: About mixins
      url: "https://github.com/monitoring-mixins/docs"
      weight: 2
    - name: "GitHub"
      url: "https://github.com/observeproject/sites"
      weight: 3

