{
 "title": "Grafana Agent Flow / Controller",
 "tags": [ "grafana-agent-flow-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki Data Source", "query": "loki" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(agent_component_controller_running_components, cluster)\n"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(agent_component_controller_running_components{cluster=\"$cluster\"}, namespace)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running agents",
   "type": "stat",
   "description": "The number of Grafana Agent Flow instances whose metrics are being sent and reported.\n",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "agents" } },
   "targets": [
    {
     "expr": "count(agent_component_controller_evaluating{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running components",
   "type": "stat",
   "description": "The number of running components across all running agents.\n",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "components" } },
   "targets": [
    {
     "expr": "sum(agent_component_controller_running_components{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall component health",
   "type": "stat",
   "description": "The percentage of components which are in a healthy state.\n",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(agent_component_controller_running_components{cluster=\"$cluster\", namespace=\"$namespace\",health_type=\"healthy\"}) /\nsum(agent_component_controller_running_components{cluster=\"$cluster\", namespace=\"$namespace\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Components by health",
   "type": "bargauge",
   "description": "Breakdown of components by health across all running agents.\n\n* Healthy: components have been evaluated completely and are reporting themselves as healthy.\n* Unhealthy: Components either could not be evaluated or are reporting themselves as unhealthy.\n* Unknown: A component has been created but has not yet been started.\n* Exited: A component has exited. It will not return to the running state.\n\nMore information on a component's health state can be retrieved using\nthe Grafana Agent Flow UI.\n\nNote that components may be in a degraded state even if they report\nthemselves as healthy. Use component-specific dashboards and alerts\nto observe detailed information about the behavior of a component.\n",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum(agent_component_controller_running_components{cluster=\"$cluster\", namespace=\"$namespace\", health_type=\"healthy\"}) or vector(0)",
     "legendFormat": "Healthy"
    },
    {
     "expr": "sum(agent_component_controller_running_components{cluster=\"$cluster\", namespace=\"$namespace\", health_type=\"unhealthy\"}) or vector(0)",
     "legendFormat": "Unhealthy"
    },
    {
     "expr": "sum(agent_component_controller_running_components{cluster=\"$cluster\", namespace=\"$namespace\", health_type=\"unknown\"}) or vector(0)",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sum(agent_component_controller_running_components{cluster=\"$cluster\", namespace=\"$namespace\", health_type=\"exited\"}) or vector(0)",
     "legendFormat": "Exited"
    }
   ]
  },
  {
   "title": "Component evaluation rate",
   "type": "timeseries",
   "description": "The frequency at which components get updated.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(agent_component_evaluation_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Component evaluation time",
   "type": "timeseries",
   "description": "The percentiles for how long it takes to complete component evaluations.\n\nComponent evaluations must complete for components to have the latest\narguments. The longer the evaluations take, the slower it will be to\nreconcile the state of components.\n\nIf evaluation is taking too long, consider sharding your components to\ndeal with smaller amounts of data and reuse data as much as possible.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(agent_component_evaluation_seconds_bucket{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(agent_component_evaluation_seconds_bucket{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "sum(rate(agent_component_evaluation_seconds_sum{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) /\nsum(rate(agent_component_evaluation_seconds_count{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]))\n",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Component evaluation histogram",
   "type": "heatmap",
   "description": "Detailed histogram view of how long component evaluations take.\n\nThe goal is to design your config so that evaluations take as little\ntime as possible; under 100ms is a good goal.\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "sum by (le) (increase(agent_component_evaluation_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Component dependency wait histogram",
   "type": "heatmap",
   "description": "Detailed histogram of how long components wait to be evaluated after their dependency is updated.\n\nThe goal is to design your config so that most of the time components do not\nqueue for long; under 10ms is a good goal.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (le) (increase(agent_component_dependencies_wait_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}