---
name: Pull request CI workflow

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17'
    - run: make generate
