---
name: CI workflow

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-go@v4.1.0
      with:
        go-version: '^1.21'
    - run: make
